//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Exam = new HashSet<Exam>();
        }
    
        public int Id_emp { get; set; }
        public Nullable<int> Id_dep { get; set; }
        public string Surname { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_tit { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Chef { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exam { get; set; }
    }
}
