//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id_req { get; set; }
        public Nullable<int> Id_disc { get; set; }
        public Nullable<int> Id_spec { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
