//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NF_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public int ID { get; set; }
        public string Name_specialization { get; set; }
    }
}
